### ISSUE TITLE
Structure and redesign the Artist HTML page layout for all the API information

### ISSUE THREAD

**Issue by JSirisavath** [dakota-bruffett/Project_3_Apis#10]
Add CSS and necessary HTML tags, to display API information correctly

**Comment by JSirisavath** [comment]
#26

**Comment by cr7st74n** [comment]
Hey, I checked it out and it looks great, I love the implementation of the tracks and the design is great. The buttons are still difficult to read, but is just that minor change of color that we will have to do. Thank  you!

**Comment by JSirisavath** [comment]
Pull req #33 merged into main.
