### ISSUE TITLE
Implement a save button function 

### ISSUE THREAD

**Issue by JSirisavath** [dakota-bruffett/Project_3_Apis#13]
Make the save button work to call the Flask server to make a  post request to the database

**Comment by JSirisavath** [comment]
Inclduing the HTML BTN

**Comment by cr7st74n** [comment]
I currently working in this problem, and also the back-end part. I already added the HTML btn.

**Comment by JSirisavath** [comment]
Update: Need all data from API calls being saved to db

**Comment by JSirisavath** [comment]
Part of issue #9 , since it is practically in the same realm of issues
