### ISSUE TITLE
Connecting YouTube API with other modules.

### ISSUE THREAD

**Issue by RichardJThies** [dakota-bruffett/Project_3_Apis#22]
Need to make sure the rest of the program has access to the API module.

**Comment by JSirisavath** [comment]
@RichardJThies , where you able to make a pull req on what you have for the YT API yet? I know you had version 1 implemented from pull req, #21 , but also add more connections to the app.py and artist.html  template

**Comment by RichardJThies** [comment]
I just did now

**Comment by JSirisavath** [comment]
#37
