### ISSUE TITLE
Error handling for API Modules 

### ISSUE THREAD

**Issue by RichardJThies** [dakota-bruffett/Project_3_Apis#23]
Need to improve the error handling of the YouTube API module.

**Comment by JSirisavath** [comment]
Rrestructure modules to handle error handling: Example repo from Richard: https://github.com/RichardJThies/flask_github_beginning

Examples of error handling to think about from Clara's notes: 
Your app has error handling. What if no internet? What if one API is down and the others are working? What if an API returns an unexpected response? What if the user enters an invalid date or a non-existent city? What else could go wrong?

**Comment by cr7st74n** [comment]
I successfully add an error handling for the Musicbrainz API !

**Comment by JSirisavath** [comment]
@cr7st74n , thank you!  I will take a look at the pull request when made

**Comment by JSirisavath** [comment]
Spotify's API Module Error handling pull req: #45

**Comment by JSirisavath** [comment]
#47  (Youtube API Module)  was merged and #45 (Spotify API Module) was merged. And error handling  was added in  #30  (MusicBrainz API)
